spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

app:
  bootstrap:
    admin:
      username: ${BOOTSTRAP_ADMIN_USERNAME:admin}
      password: ${BOOTSTRAP_ADMIN_PASSWORD:Admin@123}
      email: ${BOOTSTRAP_ADMIN_EMAIL:admin@clinic.local}
